apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.gadgets.muntashirislam.com
spec:
  group: gadgets.muntashirislam.com
  version: v1
  groupPriorityMinimum: 2000
  versionPriority: 10
  insecureSkipTLSVerify: true
  service:
    name: gadget-server
    namespace: gadgets
